"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var ARTICLES_QUERY = exports.ARTICLES_QUERY = "\n  query GetArticles($first: Int!, $after: String) {\n    shop {\n      articles(first: $first, after: $after) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            author {\n              bio\n              email\n              firstName\n              lastName\n              name\n            }\n            blog {\n              id\n            }\n            comments(first: 250) {\n              edges {\n                node {\n                  author {\n                    email\n                    name\n                  }\n                  content\n                  contentHtml\n                  id\n                }\n              }\n            }\n            content\n            contentHtml\n            excerpt\n            excerptHtml\n            id\n            image {\n              altText\n              id\n              src\n            }\n            publishedAt\n            tags\n            title\n            url\n          }\n        }\n      }\n    }\n  }\n";

var BLOGS_QUERY = exports.BLOGS_QUERY = "\n  query GetBlogs($first: Int!, $after: String) {\n    shop {\n      blogs(first: $first, after: $after) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            id\n            title\n            url\n          }\n        }\n      }\n    }\n  }\n";

var COLLECTIONS_QUERY = exports.COLLECTIONS_QUERY = "\n  query GetCollections($first: Int!, $after: String) {\n    shop {\n      collections(first: $first, after: $after) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            description\n            descriptionHtml\n            handle\n            id\n            image {\n              altText\n              id\n              src\n            }\n            products(first: 250) {\n              edges {\n                node {\n                  id\n                }\n              }\n            }\n            title\n            updatedAt\n          }\n        }\n      }\n    }\n  }\n";

var PRODUCTS_QUERY = exports.PRODUCTS_QUERY = "\n  query GetProducts($first: Int!, $after: String) {\n    shop {\n      products(first: $first, after: $after) {\n        pageInfo {\n          hasNextPage\n        }\n        edges {\n          cursor\n          node {\n            createdAt\n            description\n            descriptionHtml\n            handle\n            id\n            images(first: 250) {\n              edges {\n                node {\n                  id\n                  altText\n                  originalSrc\n                }\n              }\n            }\n            onlineStoreUrl\n            options {\n              id\n              name\n              values\n            }\n            priceRange {\n              minVariantPrice {\n                amount\n                currencyCode\n              }\n              maxVariantPrice {\n                amount\n                currencyCode\n              }\n            }\n            productType\n            publishedAt\n            tags\n            title\n            updatedAt\n            variants(first: 250) {\n              edges {\n                node {\n                  availableForSale\n                  compareAtPrice\n                  id\n                  image {\n                    altText\n                    id\n                    originalSrc\n                  }\n                  price\n                  selectedOptions {\n                    name\n                    value\n                  }\n                  sku\n                  title\n                  weight\n                  weightUnit\n                }\n              }\n            }\n            vendor\n          }\n        }\n      }\n    }\n  }\n";

var SHOP_POLICIES_QUERY = exports.SHOP_POLICIES_QUERY = "\n  query GetPolicies {\n    shop {\n      privacyPolicy {\n        body\n        id\n        title\n        url\n      }\n      refundPolicy {\n        body\n        id\n        title\n        url\n      }\n      termsOfService {\n        body\n        id\n        title\n        url\n      }\n    }\n  }\n";